INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('TBL_CD', '00102', 'TFMS_DIDOHIST_DTL', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('AUTH_CD', '00', '전체권한', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('AUTH_CD', '01', '관리자', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('AUTH_CD', '02', '일반사용자', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'CD_NM_CD', '코드별 설명', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'AUTH_CD', '권한정보', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'CONTROL_CD', '제어정보', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'CTL_CD', '제어정보', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'DEPT_CD', '부서코드', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'EVENT_CD', '이벤트코드', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'FCLT_CD', '장비코드', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'POSITION_CD', '직책코드', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'SITE_TYPE_CD', '국소종류', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'SNSR_CD', '센서구분', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'SNSR_TYPE', '센서종류', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'TBL_CD', '히스토리 테이블 정보', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'STATUS_CD', '상태코드', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CD_NM_CD', 'WORK_CD', '근무코드', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '11', '지역 설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '12', '설비 설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '13', '센서 설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '14', 'AI임계치설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '15', 'DI임계치설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '16', 'DO제어', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '17', '장애delay설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '18', '실시간감시설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '19', '사용자설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '20', '메시지설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '21', '영상설정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_TYPE_CD', '40', '모니터링 데이터 요청', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '00', 'Off', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '01', 'On', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '10', '추가', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '11', '수정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '12', '삭제', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '13', '요청', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '14', '중지요청', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '15', '강제종료', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '17', '종료', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '18', '리셋', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('DEPT_CD', '00', '전파계획과', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('DEPT_CD', '01', '전파관리과', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('DEPT_CD', '02', '전파보호과', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('DEPT_CD', '03', '지원과', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('DEPT_CD', '04', '전파운용팀', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_GRADE_CD', '99', '알수없음', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_GRADE_CD', '00', '정상', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_GRADE_CD', '01', '주의', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_GRADE_CD', '02', '경고', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_GRADE_CD', '03', '위험', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_STATUS_CD', '00', '진행', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_STATUS_CD', '01', '자동복구', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('EVT_STATUS_CD', '02', '강제복구', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FAULT_CD', '01', '네트워트장애', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FAULT_CD', '02', '응답없음', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FAULT_CD', '00', '정상', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FCLT_CD', '001', '데이터수집장치', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FCLT_CD', '002', '영상', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FCLT_CD', '011', '고정감시SBC ', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FCLT_CD', '012', '고정감시운용', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FCLT_CD', '013', '준고정', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('FCLT_CD', '014', '고정방탐', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '00', 'Region_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '01', 'RTU_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '02', 'RTU_02', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '03', 'DVR_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '04', 'Heat_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '05', 'smoke_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '06', 'water_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '07', 'door_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '08', 'aircon_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '09', 'light_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '10', 'DVR_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '11', 'volt_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '12', 'TEMP_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '13', 'hum_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '14', 'Ant_01', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('ICON_CD', '15', 'Region_02', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('IMG_SUB_TYPE', '00', 'BMP', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('IMG_SUB_TYPE', '01', 'JPG', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('IMG_SUB_TYPE', '02', 'PNG', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('IMG_TYPE', '00', '아이콘', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('IMG_TYPE', '01', '배경', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('POSITION_CD', '00', '서기보', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('POSITION_CD', '01', '서기', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('POSITION_CD', '02', '주사보', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('POSITION_CD', '03', '주사보', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('POSITION_CD', '04', '사무관', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('POSITION_CD', '05', '팀장', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('POSITION_CD', '06', '과장', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SITE_CD', '10', '본소', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SITE_CD', '21', '전파관리소', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SITE_CD', '22', '센터', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SITE_CD', '30', '사무국', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SITE_CD', '40', '원격국', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '100', '열감지', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '101', '연기감지', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '102', '누수감지', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '103', '출입문', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '104', '영상녹화 ON/OFF', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '200', '냉난방기 ON/OFF', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '201', '전등 ON/OFF', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '202', '감시장비-전원 ON/OFF', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '400', '감시장비-고정측정기#1', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '401', '감시장비-고정측정기#2', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '402', '감시장비-고정측정기#3', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '403', '감시장비-고정측정기#4', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '404', '감시장비-안테나제어기', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '405', '감시장비-음성복조장치', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '406', '감시장비-신호처리장치', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '420', '감시운영SW-고정감시운영상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '421', '감시운영SW-본소DB연결상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '422', '감시운영SW-지소DB연결상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '423', '감시운영SW-메인데몬 실행상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '424', '감시운영SW-전파품질데몬 실행상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '425', '감시운영SW-불법전파탐사데몬 실행상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '426', '감시운영SW-이용률데몬 실행상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '427', '감시운영SW-운용감시데몬 실행상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '428', '감시운영SW-음성서버 연결상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '429', '감시운영SW-원복프로세스 실행상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '440', '준고정-측정수신기', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '441', '준고정-디지털처리부', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '442', '준고정-문열림상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '460', '고정방탐-방탐처리기', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '461', '고정방탐-방탐수신기1', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '462', '고정방탐-방탐수신기2', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '463', '고정방탐-방탐수신기3', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '464', '고정방탐-방탐수신기4', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '465', '고정방탐-방탐수신기5', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '466', '고정방탐-시스템상태', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '467', '고정방탐-신호처리장치', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '300', '온도', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '301', '습도', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '302', '상전압Vr', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '303', '상전압Vs', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '304', '상전압Vt', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_SUB_TYPE', '305', '주파수', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_TYPE', '00', 'AI', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_TYPE', '01', 'DI', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_TYPE', '02', 'DO', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_TYPE', '03', '감시장비', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('STATUS_CD', '00', '연결중', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('STATUS_CD', '01', '연결종료', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('STATUS_CD', '02', '비정상종료', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('STATUS_CD', '03', '강제 종료', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('TBL_CD', '00100', 'TFMS_AIHIST_DTL', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('TBL_CD', '00101', 'TFMS_DIDOHIST_DTL', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('TBL_CD', '01103', 'TFMS_FREHIST_DTL', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('TBL_CD', '01203', 'TFMS_FRSHIST_DTL', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('TBL_CD', '01303', 'TFMS_SREHIST_DTL', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('TBL_CD', '01403', 'TFMS_FDEHIST_DTL', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('WORK_CD', '00', '근무', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('WORK_CD', '01', '퇴사', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('WORK_CD', '02', '휴직', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '16', '시작', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('CTL_CMD_CD', '19', '일시정지', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_HW_CD', '01', '외부전원제어기', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('SNSR_HW_CD', '02', '내부전원제어기', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('COMPANY_CD', '01', 'A&D', 'Y');

INSERT INTO CCSFMS.TFMS_COM_CD
  (CD_ID, CD_VAL, CD_NM, SYN_CD)
VALUES
  ('COMPANY_CD', '02', 'Allimsystem', 'Y');

