/*
// -----------------------------------------변경전
eSNSRSUB_AI_PowerVR=302, // 상전압Vr
eSNSRSUB_AI_PowerVS,     // 상전압Vs
eSNSRSUB_AI_PowerVT,     // 상전압Vt
eSNSRSUB_AI_PowerFreq,   // 주파수

// -----------------------------------------변경후
eSNSRSUB_AI_Power=302,     // 전원감시 : 상전압Vr, 상전류Ir, 상전류Is, 주파수Hz  .. -- 세부 센서구분은 SNSR_IDX 컬럼을 활용
*/
-- SELECT * FROM TFMS_SNSR_MST WHERE SNSR_SUB_TYPE='302' OR SNSR_SUB_TYPE='303' OR SNSR_SUB_TYPE='304' OR SNSR_SUB_TYPE='305';

-----------------------------------------------------------------
-- 작업순서1) 

-----상전압R
INSERT INTO TFMS_SNSRMETHOD_MST (SNSR_ID, SITE_ID, PORT, S01_POS, CREATE_DATE, UPDATE_DATE, SYN_CD)
    SELECT f.SNSR_ID,  f.SITE_ID, '', CHR(1), SYSDATE, SYSDATE, 'I' FROM (SELECT * FROM TFMS_SNSR_MST WHERE SNSR_SUB_TYPE='302') f
WHERE NOT EXISTS ( SELECT b.SNSR_ID FROM TFMS_SNSR_MST a, TFMS_SNSRMETHOD_MST b WHERE a.SNSR_ID=b.SNSR_ID AND a.SNSR_SUB_TYPE='302');

-----상전압S
INSERT INTO TFMS_SNSRMETHOD_MST (SNSR_ID, SITE_ID, PORT, S01_POS, CREATE_DATE, UPDATE_DATE, SYN_CD)
    SELECT f.SNSR_ID,  f.SITE_ID, '', CHR(7), SYSDATE, SYSDATE, 'I' FROM (SELECT * FROM TFMS_SNSR_MST WHERE SNSR_SUB_TYPE='303') f
WHERE NOT EXISTS ( SELECT b.SNSR_ID FROM TFMS_SNSR_MST a, TFMS_SNSRMETHOD_MST b WHERE a.SNSR_ID=b.SNSR_ID AND a.SNSR_SUB_TYPE='303');

-----상전압T
INSERT INTO TFMS_SNSRMETHOD_MST (SNSR_ID, SITE_ID, PORT, S01_POS, CREATE_DATE, UPDATE_DATE, SYN_CD)
    SELECT f.SNSR_ID,  f.SITE_ID, '', CHR(8), SYSDATE, SYSDATE, 'I' FROM (SELECT * FROM TFMS_SNSR_MST WHERE SNSR_SUB_TYPE='304') f
WHERE NOT EXISTS ( SELECT b.SNSR_ID FROM TFMS_SNSR_MST a, TFMS_SNSRMETHOD_MST b WHERE a.SNSR_ID=b.SNSR_ID AND a.SNSR_SUB_TYPE='304');

-----주파수
INSERT INTO TFMS_SNSRMETHOD_MST (SNSR_ID, SITE_ID, PORT, S01_POS, CREATE_DATE, UPDATE_DATE, SYN_CD)
    SELECT f.SNSR_ID,  f.SITE_ID, '', CHR(13), SYSDATE, SYSDATE, 'I' FROM (SELECT * FROM TFMS_SNSR_MST WHERE SNSR_SUB_TYPE='305') f
WHERE NOT EXISTS ( SELECT b.SNSR_ID FROM TFMS_SNSR_MST a, TFMS_SNSRMETHOD_MST b WHERE a.SNSR_ID=b.SNSR_ID AND a.SNSR_SUB_TYPE='305');
COMMIT;

---------------------------------------------------------------
-- 작업순서2)
UPDATE TFMS_SNSR_MST SET SNSR_IDX='1' WHERE SNSR_SUB_TYPE='303';
UPDATE TFMS_SNSR_MST SET SNSR_IDX='2' WHERE SNSR_SUB_TYPE='304';
UPDATE TFMS_SNSR_MST SET SNSR_IDX='3' WHERE SNSR_SUB_TYPE='305';
COMMIT;

/*
==============================
상전압Vr -- 1
상전류Ir -- 7
상전류Is -- 8
주파수Hz -- 13

상전압R ==> 상전압Vr
상전압S ==> 상전류Ir
상전압T ==> 상전류Is
주파수 ==> 주파수Hz
*/

---------------------------------------------------------------
-- 작업순서3) 이름변경
UPDATE TFMS_SNSR_MST SET SNSR_NM='상전압Vr' WHERE SNSR_SUB_TYPE='302';
UPDATE TFMS_SNSR_MST SET SNSR_NM='상전류Ir' WHERE SNSR_SUB_TYPE='303';
UPDATE TFMS_SNSR_MST SET SNSR_NM='상전류Is' WHERE SNSR_SUB_TYPE='304';
UPDATE TFMS_SNSR_MST SET SNSR_NM='주파수Hz' WHERE SNSR_SUB_TYPE='305';
COMMIT;

--- 작업순서4)
UPDATE TFMS_SNSR_MST SET SNSR_SUB_TYPE='302' 
WHERE SNSR_SUB_TYPE='302' OR SNSR_SUB_TYPE='303' OR SNSR_SUB_TYPE='304' OR SNSR_SUB_TYPE='305';